language: java

# Multi-os in beta
os:
  - linux
  - osx

branches:
  only:
    - master
    - /^release.*$/

jdk:
  - oraclejdk7
  - openjdk7
  - oraclejdk8

sudo: false

install: 
  - ./gradlew wrapper
  - ./gradlew dependencies

script:
  - ./gradlew build
  - ./gradlew installMiniDist
